'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs');
const E=require('./timeline-export-api'),B=require('./director-render-bridge'),P=require('./director-previs-model'),G=require('./director-layout-guide');
function fixture(){const scene={id:'room',projectId:'p',name:'舱室',imageUrl:'/assets/room.png'},space=P.newSpace(scene);const shot={id:'s',projectId:'p',sceneIds:['room'],characterIds:[],propIds:[],script:'无对白空间镜头',dialogue:'',sourceExcerpt:'',dur:5};const data={projects:[{id:'p',h3Width:864,h3Height:480,directorSpaces:[space]}],shots:[shot],scenes:[scene],characters:[],props:[],jobs:[],audio:[]};const plan=P.newPlan(shot,space,[]);plan.purpose='建立空间';shot.directorPlan=plan;plan.binding=P.binding(shot);return {data,shot,plan};}
test('480p export is explicit and legacy HD defaults remain intact',()=>{const p=E.outputSettings('854x480');assert.equal(p.width,854);assert.equal(p.height,480);assert.equal(p.upscaled,false);assert.equal(E.outputSettings().preset,'1280x720');assert.match(p.label,/480p/);});
test('480-line delivery declares exact 16:9 display with rational sample aspect',()=>{const p=E.outputSettings('854x480'),[n,d]=p.sampleAspect.split('/').map(Number);assert.equal(p.width*n*9,p.height*d*16);assert.match(E.outputScaleFilter(p),/setsar=1280\/1281/);assert.match(E.intermediateFilter(p,'crop'),/crop=854:480,setsar=1280\/1281/);});
test('ordinary HD and QHD filters do not inherit non-square 480p sample aspect',()=>{for(const size of ['1280x720','1920x1080','2560x1440'])assert.match(E.outputScaleFilter(size),/setsar=1,/);});
test('director frame and video sizes inherit selected project, not hardcoded 576p',()=>{const f=fixture(),refs=B.references(f.data,f.shot),r=B.frameRequest(f.data,f.shot,refs.map(a=>({...a,file:'ams-ref-'+ 'a'.repeat(64)+'.png'})));assert.deepEqual(B.dimensions(f.data,f.shot),{width:864,height:480});assert.equal(r.height,480);assert.equal(r.width,864);});
test('explicit per-shot dimensions retain priority, malformed grids fail early',()=>{const f=fixture();f.shot.width=1024;f.shot.height=576;assert.deepEqual(B.dimensions(f.data,f.shot),{width:1024,height:576});for(const width of [0,854,Infinity,-864]){f.shot.width=width;assert.throws(()=>B.dimensions(f.data,f.shot),/尺寸/);}});
test('changing project sampling size invalidates previous frame-review signature',()=>{const f=fixture(),key=B.frameKey(f.data,f.shot);f.data.projects[0].h3Width=1024;f.data.projects[0].h3Height=576;assert.notEqual(B.frameKey(f.data,f.shot),key);});
test('geometric control guide actually renders at480 lines rather than only relabeling',()=>{const f=fixture(),g=G.geometry(f.plan,{width:864,height:480}),svg=G.svg(f.plan,{width:864,height:480});assert.equal(g.width,864);assert.equal(g.height,480);assert.match(svg,/width="864" height="480" viewBox="0 0 864 480"/);assert.doesNotMatch(svg,/width="1024"/);});
test('UI supports480p only after backend confirms the profile',()=>{const source=fs.readFileSync('timeline-edit-ui.js','utf8');assert.match(source,/value="854x480" disabled/);assert.match(source,/CUT.outputProfiles\|\|\['1280x720'\]/);assert.match(source,/'854x480','1280x720'/);});

test('visual-guidance changes invalidate first-frame inspection as well as dimensions',()=>{const f=fixture(),key=B.frameKey(f.data,f.shot);f.shot.directorVisualGuidance='Change action props and room view';assert.notEqual(B.frameKey(f.data,f.shot),key);});
