'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),P=require('./director-previs-model'),B=require('./director-render-bridge'),F=require('./frame-provenance'),C=require('./performance-audio-contract');
function fixture(){const scene={id:'room',projectId:'p',name:'Room',imageUrl:'/assets/room.png'},space=P.newSpace(scene);const characters=['a','b','c','v'].map((id,i)=>({id,name:['父亲','母亲','女儿','广播'][i],projectId:'p',imageUrl:'/assets/'+id+'.png',type:id==='v'?'仅声音':'角色'}));const old={id:'source',projectId:'p',sceneIds:['room'],characterIds:['a','b','c'],propIds:[],assetStates:{},script:'父亲说话，母女听。',dialogue:'父亲：请看原版。',sourceExcerpt:'父亲：请看原版。',dur:6,videoUrl:'/original.mp4',firstFrameUrl:'/original.png',performanceAudio:{file:'old.wav'}};const data={projects:[{id:'p',directorSpaces:[space]}],shots:[old],characters,scenes:[scene],props:[],audio:[],jobs:[]},plan=P.newPlan(old,space,characters);plan.purpose='看见三人的关系';plan.actors.forEach((a,i)=>{a.start.x=1.5+i*1.5;a.end=P.clone(a.start);});old.directorPlan=plan;const r=B.cloneTrial(data,old,{id:'trial',batchId:'trial-batch'});return {original:data,source:old,data:r.data,shot:r.shot};}
function reviewed(f){const s=f.shot;s.firstFrameUrl='/assets/candidate.png';s.firstFrameSpeakerPosition='left';s.firstFrameProvenance=F.create(s,B.references(f.data,s),s.firstFrameUrl);s.directorFrameReview={source:B.frameKey(f.data,s),imageUrl:s.firstFrameUrl,reviewer:'assistant_visual_inspection',at:'2026-10-10T00:00:00Z',visibleCharacterIds:['a','b','c'],speakerId:'a',speakerPosition:'left',checks:{identities:true,count:true,wardrobe:true,blocking:true,space:true}};return f;}
const frame={file:'ams-ref-'+ 'c'.repeat(64)+'.png',speakerPosition:'left'};
function binding(f){const events=B.context(f.data,f.shot).events;return {version:1,file:'ams-audio-'+ 'd'.repeat(64)+'.wav',sha256:'d'.repeat(64),duration:6,frames:C.frames(6),speechKey:C.speechKey(events)};}
test('cloned trial retains all three cast but not stale video, first frame, or lip binding',()=>{const f=fixture();assert.equal(f.shot.characterIds.length,3);assert.equal(f.shot.isDirectorTrial,true);for(const k of ['videoUrl','firstFrameUrl','performanceAudio'])assert.equal(f.shot[k],undefined);assert.equal(f.source.videoUrl,'/original.mp4');assert.equal(f.original.shots.length,1);});
test('one speaking voice does not erase the two listening visual references',()=>{const f=fixture();assert.equal(B.references(f.data,f.shot).filter(r=>r.kind==='characters').length,3);assert.match(B.openingPrompt(f.data,f.shot),/Visible physical people in this shot: 3/);});
test('project generation hold is honored by all preparation',()=>{const f=fixture();f.data.projects[0].productionPolicy={generationHold:true};assert.throws(()=>B.references(f.data,f.shot),/暂停/);});
test('planning-only flag cannot be used to submit a dynamic trial',()=>{const f=fixture();f.shot.directorPrevisOnly=true;assert.throws(()=>B.context(f.data,f.shot),/调度样镜/);});
test('existing source IDs cannot be overwritten by creating a trial',()=>{const f=fixture();assert.throws(()=>B.cloneTrial(f.data,f.shot,{id:'source',batchId:'new'}),/覆盖/);});
test('missing scene or cast image fails before any render request',()=>{const f=fixture();delete f.data.characters[1].imageUrl;assert.throws(()=>B.references(f.data,f.shot),/缺少/);});
test('raw first-frame candidate is not treated as inspected',()=>{const f=fixture();assert.throws(()=>B.checkFrame(f.data,f.shot,null),/重新检查/);});
test('wrong visible count or a missed identity check blocks production',()=>{let f=reviewed(fixture());f.shot.directorFrameReview.visibleCharacterIds=['a','b'];assert.throws(()=>B.checkFrame(f.data,f.shot,f.shot.directorFrameReview),/可见人物/);f=reviewed(fixture());f.shot.directorFrameReview.checks.identities=false;assert.throws(()=>B.checkFrame(f.data,f.shot,f.shot.directorFrameReview),/identities/);});
test('asset image change makes a previous visual inspection stale',()=>{const f=reviewed(fixture());f.data.characters[0].imageUrl='/assets/a-v2.png';assert.throws(()=>B.checkFrame(f.data,f.shot,f.shot.directorFrameReview),/来源已变化/);});
test('speaker position must come from inspected pixels rather than be defaulted to center',()=>{const f=reviewed(fixture());f.shot.firstFrameSpeakerPosition='center';assert.throws(()=>B.checkFrame(f.data,f.shot,f.shot.directorFrameReview),/位置/);});
test('dialogue video needs actual performance binding',()=>{const f=reviewed(fixture());assert.throws(()=>B.renderRequest(f.data,f.shot,{firstFrame:frame,jobId:'j'}),/绑定已核对/);});
test('render payload keeps ensemble instructions and exactly one intended speaker',()=>{const f=reviewed(fixture()),b=binding(f),r=B.renderRequest(f.data,f.shot,{firstFrame:frame,binding:b,jobId:'j'});assert.match(r.prompt,/Visible physical people in this shot: 3/);assert.match(r.prompt,/other visible people react without mouthing/);assert.equal(r.dialogueEvents.length,1);assert.equal(r.firstFrame.speakerPosition,'left');assert.equal(r.performanceAudio,b);assert.equal(r.mode,'I2VA');});
test('wrong speaker binding is rejected while original data remain unchanged',()=>{const f=reviewed(fixture()),before=P.signature(f.data),b=binding(f);b.speechKey='other';assert.throws(()=>B.renderRequest(f.data,f.shot,{firstFrame:frame,binding:b,jobId:'j'}),/台词/);assert.equal(P.signature(f.data),before);});
test('upload set must include the exact per-shot assets',()=>{const f=fixture();assert.throws(()=>B.frameRequest(f.data,f.shot,[]),/不一致/);});
test('three-person staging uses scene plus outer cast first, then remaining person without deleting them',()=>{const f=fixture(),refs=B.references(f.data,f.shot),passes=B.framePasses(refs);assert.equal(passes[0][0].kind,'scenes');assert.equal(passes[0].length,3);assert.equal(passes.length,2);assert.equal(new Set(passes.flat().map(r=>r.assetId)).size,refs.length);assert.equal(passes.flat().length,refs.length);});
test('frame payload only uses parameters understood by the existing AMS API',()=>{const f=fixture(),refs=B.references(f.data,f.shot);const req=B.frameRequest(f.data,f.shot,refs.map(r=>({...r,file:'ams-ref-'+ 'a'.repeat(64)+'.png'})));assert.equal(req.compositionVersion,undefined);assert.equal(req.references.length,4);});
