'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),M=require('./director-previs-model');
function fixture(){const scene={id:'room',projectId:'p',name:'船舱'},space=M.newSpace(scene);space.fixtures=[{id:'door',kind:'door',label:'入口',x:3,y:5,w:.9,h:.2},{id:'table',kind:'table',label:'餐桌',x:3,y:2.6,w:1.7,h:.8}];const chars=['a','b','c','voice'].map((id,i)=>({id,projectId:'p',name:['父亲','母亲','女儿','广播'][i],type:id==='voice'?'仅声音':'角色'}));const shot={id:'s',projectId:'p',sceneIds:['room'],characterIds:['a','b','c'],script:'父亲提问，母女听。',dialogue:'父亲：请看原版。',visual:'旧版单人描述',camera:'旧版中心机位',dur:6,videoUrl:'/old.mp4',firstFrameUrl:'/old.png',firstFrameSpeakerPosition:'center',performanceAudio:{file:'existing.wav'},prompt:'Old manual prompt',storyboardBatchId:'batch',assetStates:{}};const data={activeProjectId:'p',projects:[{id:'p',name:'本片',directorSpaces:[space]},{id:'q',name:'其他项目'}],shots:[shot,{id:'next',projectId:'p',storyboardBatchId:'batch',continueFromShotId:'s',videoUrl:'/next.mp4'},{id:'s',projectId:'q',videoUrl:'/foreign.mp4'}],characters:[...chars,{id:'x',projectId:'q',name:'外部人物'}],scenes:[scene],jobs:[],generations:[{projectId:'p',shot:'s',videoUrl:'/original-take.mp4',status:'MASTER'}]};const plan=M.newPlan(shot,space,chars);plan.purpose='看到一家三口的分歧';plan.camera.start={x:3,y:6,targetX:3,targetY:2};plan.camera.end=M.clone(plan.camera.start);plan.actors.forEach((a,i)=>{a.start={x:1.5+i*1.5,y:2,facing:180,pose:'seated'};a.end=M.clone(a.start);});const events=[{type:'speech',speakerId:'a',speakerName:'父亲',delivery:'onscreen',text:'请看原版。'}];return {data,scene,space,chars,shot,plan,events};}
function apply(f){return M.applyPlan(f.data,'p','s',f.plan,M.signature(f.shot),f.events);}
test('draft imports three physical actors without fabricating assets or changing source',()=>{const f=fixture(),before=M.signature(f.data);assert.equal(f.plan.actors.length,3);assert.equal(f.plan.revision,0);assert.equal(M.signature(f.data),before);});
test('perspective derives screen side from camera instead of permanently pinning a character left',()=>{const p={x:1,y:2};assert.equal(M.projectPoint(p,{x:3,y:6,targetX:3,targetY:2},65).side,'left');assert.equal(M.projectPoint(p,{x:3,y:-2,targetX:3,targetY:2},65).side,'right');});
test('points behind the camera are excluded from the indicated frame',()=>assert.equal(M.projectPoint({x:3,y:8},{x:3,y:6,targetX:3,targetY:2},65).inFrame,false));
test('motion interpolation preserves endpoints and does not add people',()=>{const {plan}=fixture();plan.actors[0].end.x=4;assert.equal(M.position(plan.actors[0],0).x,1.5);assert.equal(M.position(plan.actors[0],1).x,4);assert.equal(M.position(plan.actors[0],.5).x,2.75);assert.equal(plan.actors.length,3);});
test('nonfinite camera values and zero viewing vector are hard errors',()=>{for(const bad of [NaN,Infinity]){const f=fixture();f.plan.camera.fov=bad;assert.ok(M.issues(f.plan,f.shot,{},f.chars,f.events).some(x=>x.level==='error'));}const f=fixture();f.plan.camera.start.targetY=6;assert.throws(()=>M.assertReady(f.plan,f.shot,{},f.chars,f.events),/机位/);});
test('foreign and duplicate characters cannot be applied',()=>{let f=fixture();f.plan.actors.push(M.clone(f.plan.actors[0]));assert.throws(()=>apply(f),/两个/);f=fixture();f.plan.actors[0].characterId='x';assert.throws(()=>apply(f),/不属于/);});
test('one speaker can coexist with three visible people',()=>{const f=fixture(),r=apply(f);assert.equal(r.shot.visibleCharacterIds.length,3);assert.equal(r.shot.sceneCharacterIds.length,3);assert.equal(r.shot.characterIds.length,3);M.assertReady(r.shot.directorPlan,r.shot,r.data.projects[0],f.chars,f.events);});
test('changing the speaking character to offscreen does not silently approve an onscreen line',()=>{const f=fixture();f.plan.actors[0].presence='offscreen';assert.throws(()=>apply(f),/画内发声者/);});
test('screen playback and narration are not counted as extra physical people',()=>{const f=fixture();f.plan.actors[2].presence='screen';const a=M.newPlan({...f.shot,characterIds:['voice']},f.space,f.chars).actors[0];assert.equal(a.presence,'absent');f.plan.actors.push(a);const r=apply(f),text=M.instructions(r.shot,r.data.projects[0],f.chars,f.events);assert.match(text,/Visible physical people in this shot: 2/);assert.match(text,/ONLY inside/);assert.match(text,/not physically in this scene/);});
test('applying directions preserves source script, old media and exact audio references',()=>{const f=fixture(),before=M.signature(f.data),r=apply(f);assert.equal(M.signature(f.data),before);assert.equal(r.shot.script,f.shot.script);assert.equal(r.shot.dialogue,f.shot.dialogue);assert.equal(r.shot.videoUrl,'/old.mp4');assert.equal(r.shot.firstFrameUrl,'/old.png');assert.deepEqual(r.shot.performanceAudio,f.shot.performanceAudio);assert.deepEqual(r.data.generations,f.data.generations);assert.equal(r.shot.firstFrameSpeakerPosition,'');assert.equal(r.shot.prompt,'');assert.equal(r.shot.directorHistory.at(-1).prompt,'Old manual prompt');});
test('dependent clips are marked for review, not deleted; other project remains byte-equivalent',()=>{const f=fixture(),r=apply(f);assert.deepEqual(r.affectedIds,['s','next']);assert.equal(r.data.shots[1].videoUrl,'/next.mp4');assert.equal(r.data.shots[1].directorMediaNeedsReview,true);assert.equal(M.signature(r.data.shots[2]),M.signature(f.data.shots[2]));assert.equal(M.signature(r.data.projects[1]),M.signature(f.data.projects[1]));});
test('changed source snapshot is rejected without mutating anything',()=>{const f=fixture();assert.throws(()=>M.applyPlan(f.data,'p','s',f.plan,'stale',f.events),/已被其他/);});
test('active jobs block direction changes including a dependent shot',()=>{const f=fixture();f.data.jobs.push({projectId:'p',shot:'next',status:'正在生成'});assert.throws(()=>apply(f),/执行中的任务/);f.data.jobs[0].status='已取消';assert.doesNotThrow(()=>apply(f));});
test('later script or duration edits invalidate applied directions until reviewed',()=>{const f=fixture(),r=apply(f);const modified={...r.shot,dur:7};assert.ok(M.issues(modified.directorPlan,modified,r.data.projects[0],f.chars,f.events).some(i=>i.code==='SOURCE_CHANGED'));});
test('shared room save increments revision and marks only actual subscribers',()=>{const f=fixture(),r=apply(f),draft=M.clone(f.space);draft.fixtures[0].x=4;const save=M.saveSpace(r.data,'p',draft,M.signature(f.space));assert.equal(save.space.revision,2);assert.deepEqual(save.affectedIds,['s']);assert.equal(save.data.shots[0].videoUrl,'/old.mp4');assert.ok(M.issues(save.data.shots[0].directorPlan,save.data.shots[0],save.data.projects[0],f.chars,f.events).some(i=>i.code==='SPACE_STALE'));});
test('shared room uses optimistic concurrency and cannot reference another project scene',()=>{const f=fixture();assert.throws(()=>M.saveSpace(f.data,'p',f.space,'stale'),/布局已变化/);const d=M.clone(f.space);d.sceneId='foreign';assert.throws(()=>M.saveSpace(f.data,'p',d,M.signature(f.space)),/当前项目/);});
test('warnings about framing and movement purpose do not become arbitrary artistic bans',()=>{const f=fixture();f.plan.camera.end.x=4;f.plan.actors[2].start.x=40;const list=M.issues(f.plan,f.shot,{},f.chars,f.events);assert.ok(list.some(x=>x.code==='FRAMING'&&x.level==='warning'));assert.ok(list.some(x=>x.code==='MOTIVATION'&&x.level==='warning'));});
test('position continuity compares prior end with next start in shared world coordinates',()=>{const f=fixture(),a={directorPlan:M.clone(f.plan)},b={directorPlan:M.clone(f.plan)};a.directorPlan.actors[0].end.x=4;assert.ok(M.continuity(a,b).some(x=>x.code==='POSITION_JUMP'));b.directorPlan.actors[0].start.x=4;assert.ok(!M.continuity(a,b).some(x=>x.code==='POSITION_JUMP'));});
test('entering a fourth actor requires an explicit entry description as a review warning',()=>{const f=fixture(),prev={directorPlan:M.clone(f.plan)},next={directorPlan:M.clone(f.plan)};const a=M.clone(f.plan.actors[0]);a.characterId='officer';next.directorPlan.actors.push(a);assert.ok(M.continuity(prev,next).some(x=>x.code==='ENTRY'));a.entryAction='从门口进入';assert.ok(!M.continuity(prev,next).some(x=>x.code==='ENTRY'));});
test('copying prior endpoints never rewrites camera or guesses across scenes',()=>{const f=fixture(),prev={directorPlan:M.clone(f.plan)};prev.directorPlan.actors[0].end.x=4;const copied=M.copyEnd(prev,f.plan);assert.equal(copied.actors[0].start.x,4);assert.deepEqual(copied.camera,f.plan.camera);prev.directorPlan.space.id='other';assert.throws(()=>M.copyEnd(prev,f.plan),/同场/);});
test('unresolved scope is empty rather than silently widening to all project shots',()=>{const f=fixture();assert.equal(M.listShots(f.data,'p','missing').length,0);assert.equal(M.listShots(f.data,'q').length,1);});
test('space validation rejects malformed dimensions and duplicate fixtures',()=>{const f=fixture();f.space.width=NaN;assert.throws(()=>M.validateSpace(f.space));f.space.width=6;f.space.fixtures.push(M.clone(f.space.fixtures[0]));assert.throws(()=>M.validateSpace(f.space));});
test('render prompt contains all visible actors and silent reaction directions',()=>{const f=fixture(),r=apply(f),compile=require('./shot-prompt').compile,prompt=compile({...r.shot,dialogueEvents:f.events},r.data.projects[0],f.chars.slice(0,3).map(c=>({assetId:c.id,name:c.name,kind:'characters'})));assert.match(prompt,/Visible physical people in this shot: 3/);assert.match(prompt,/父亲/);assert.match(prompt,/母亲/);assert.match(prompt,/女儿/);assert.match(prompt,/Do NOT turn a one-speaker audio binding into a solo portrait/);assert.ok(prompt.indexOf('SILENT DIRECTOR')<prompt.indexOf('overall_soundscape:'));});
test('initial-frame directions use start pose, not future movement',()=>{const f=fixture();f.plan.actors[0].end.x=4;const r=apply(f),text=M.frameInstructions(r.shot,r.data.projects[0],f.chars);assert.match(text,/Opening pose only/);assert.match(text,/starts at \(1.50, 2.00\), seated, ends at \(1.50, 2.00\)/);});
test('frame provenance includes director plan; old image cannot silently validate new blocking',()=>{const f=fixture(),r=apply(f),F=require('./frame-provenance'),s=r.shot;s.firstFrameProvenance=F.create(s,[],s.firstFrameUrl);F.validate(s,[]);const n=M.clone(s);n.directorPlan.actors[0].start.x+=1;assert.throws(()=>F.validate(n,[]),/过期/);});
test('legacy shots without director plans preserve the prior prompt behavior',()=>assert.doesNotMatch(require('./shot-prompt').compile({dur:5,script:'Listen silently.'},{},[]),/SILENT DIRECTOR/));
test('director UI has explicit saves, unsaved-change guard and no generation endpoints',()=>{const s=fs.readFileSync('director-previs-ui.js','utf8');assert.match(s,/workspaceFlush/);assert.match(s,/beforeunload/);assert.match(s,/setItemAsync/);assert.match(s,/data-pv=\"apply\"/);assert.doesNotMatch(s,/fetch\([^)]*(?:\/prompt|\/api\/film|\/jobs|\/api\/first-frames)/);assert.doesNotMatch(s,/userApproved\s*:\s*true/);});
test('previs is linked to live navigation, first-frame builder and generation checks',()=>{const h=fs.readFileSync('AI_MOVIE_STUDIO.html','utf8'),w=fs.readFileSync('studio-workbench.js','utf8'),f=fs.readFileSync('first-frame-ui.js','utf8'),a=fs.readFileSync('asset-reference-ui.js','utf8');assert.ok(h.indexOf('director-previs-model.js')<h.indexOf('shot-prompt.js'));assert.match(h,/director-previs-ui\.js\?v=/);assert.match(w,/DirectorPrevisUI\.canLeave/);assert.match(w,/DirectorPrevisUI\?\.activate/);assert.match(f,/DirectorPrevis\.frameInstructions/);assert.match(a,/DirectorPrevis\.assertReady/);});

test('unchanged reapplication is a no-op and never invalidates media again',()=>{const f=fixture(),first=apply(f),second=M.applyPlan(first.data,'p','s',first.shot.directorPlan,M.signature(first.shot),f.events);assert.equal(second.data,first.data);assert.equal(second.changed,false);assert.equal(second.affectedIds.length,0);});
test('saving unchanged room does not increment revision or invalidate shots',()=>{const f=fixture(),r=M.saveSpace(f.data,'p',f.space,M.signature(f.space));assert.equal(r.space.revision,1);assert.equal(r.data,f.data);assert.equal(r.changed,false);});

test('previs studies cannot render until explicitly applied, even with a complete saved plan',()=>{const f=fixture(),r=apply(f);r.shot.directorPrevisOnly=true;assert.throws(()=>M.assertReady(r.shot.directorPlan,r.shot,r.data.projects[0],f.chars,f.events),/调度样镜/);const result=M.applyPlan(r.data,'p','s',r.shot.directorPlan,M.signature(r.shot),f.events);assert.equal(result.shot.directorPrevisOnly,false);assert.doesNotThrow(()=>M.assertReady(result.shot.directorPlan,result.shot,result.data.projects[0],f.chars,f.events));});

test('central service save delegates to previs without double-tracking its already saved inputs',()=>{const s=fs.readFileSync('studio-control-ui.js','utf8'),u=fs.readFileSync('director-previs-ui.js','utf8');assert.match(s,/page.id==='previs'&&globalThis.DirectorPrevisUI/);assert.match(s,/await globalThis.DirectorPrevisUI.saveUnsaved/);assert.match(u,/if(state.dirty||state.spaceDirty||state.saving)/);assert.match(u,/async function saveUnsaved/);});
