const test=require('node:test'),assert=require('node:assert/strict'),F=require('./face-refine');
const face=(pixels=60,blur=120)=>({pixels,blur}),analysis=f=>({samples:Array.from({length:5},()=>f)});
test('automatic face refinement rejects ambiguous or absent faces, accepts consistently small faces',()=>{assert.equal(F.decide(analysis([face()])).refine,true);assert.equal(F.decide(analysis([face(160,200)])).refine,false);assert.equal(F.decide(analysis([face(160,20)])).refine,true);assert.equal(F.decide(analysis([])).refine,false);assert.equal(F.decide(analysis([face(),face()]),true).refine,false)});
test('legacy jobs stay opt-out; auto only considers unique on-screen character reference',()=>{assert.equal(F.mode(), 'off');assert.throws(()=>F.mode('bad'));assert.ok(F.eligibility({faceRefineMode:'auto',references:[{kind:'props'}]}));assert.ok(F.eligibility({faceRefineMode:'auto',references:[{kind:'characters'},{kind:'characters'}]}));assert.equal(F.eligibility({faceRefineMode:'auto',references:[{kind:'characters'}],prompt:'medium shot'}),'')});
test('full-length refinement graph keeps original audio and uses current shot and character',()=>{const graph=F.graph({id:'job',prompt:'current prompt',references:[{kind:'characters',file:'current.png'}]},'source.mp4');assert.equal(graph['1'].inputs.frame_load_cap,0);assert.equal(graph['9'].inputs.prompt,'current prompt');assert.equal(graph['6'].inputs.image,'current.png');assert.deepEqual(graph['23'].inputs.audio,['1',2]);assert.deepEqual(graph['13'].inputs.audio,['1',2]);assert.equal(graph['7'],undefined)});
test('refinement completion exposes refined video but preserves original; failures fall back',async()=>{for(const error of [false,true]){const job={id:'job'+error,originalVideoUrl:'http://local/original.mp4',faceRefine:{status:'rendering',promptId:'p'}};await F.advance(job,{comfyUrl:'http://local',persist(){},request:async()=>({p:{status:error?{status_str:'error'}:{completed:true},outputs:{23:{gifs:[{filename:'refined.mp4',subfolder:'refine'}]}}}})});assert.equal(job.originalVideoUrl,'http://local/original.mp4');assert.equal(job.faceRefine.status,error?'failed':'complete');assert.match(job.videoUrl,error?/original/:/refined/)}});
test('uncertain refinement submission is not blindly submitted again',async()=>{const job={id:'uncertain',originalVideoUrl:'original',faceRefine:{status:'submitting'}};await F.advance(job,{persist(){},request:async()=>{throw Error('must not submit')}});assert.equal(job.videoUrl,'original');assert.equal(job.faceRefine.status,'failed')});
test('single-face analysis submits once and repeated polling preserves original until completion',async()=>{
 const fs=require('fs'),path=require('path'),crypto=require('crypto'),job={id:'test-face-'+Date.now(),faceRefineMode:'auto',originalVideoUrl:'original',prompt:'shot',references:[{kind:'characters',file:'character.png'}]};
 const dir=path.join(__dirname,'.runtime/face-refine'),file=path.join(dir,crypto.createHash('sha256').update(job.id).digest('hex')+'.mp4');fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(file,'fixture');let calls=0;
 const options={persist(){},comfyUrl:'http://local',detectFaces:async()=>analysis([face()]),request:async(route)=>{
   if(route==='/object_info')return Object.fromEntries(Object.values(F.graph(job,file)).map(n=>[n.class_type,{}]));
   if(route==='/prompt'){calls++;return {prompt_id:'refined'}}
   return {refined:{status:{completed:true},outputs:{23:{gifs:[{filename:'out.mp4'}]}}}};
 }};
 try{await Promise.all([F.advance(job,options),F.advance(job,options)]);assert.equal(calls,1);assert.equal(job.videoUrl,undefined);assert.equal(job.faceRefine.status,'rendering');await F.advance(job,options);assert.equal(job.faceRefine.status,'complete');assert.equal(job.originalVideoUrl,'original')}finally{fs.unlinkSync(file)}
});
