const test=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),os=require('os'),path=require('path'),http=require('http');
const {createFirstFrameApi}=require('./first-frame-api'),{MODELS,validatePlan}=require('./local-first-frame');
const refs=[{assetId:'a',kind:'characters',name:'甲',file:'ams-ref-'+ 'a'.repeat(64)+'.png'}];
const png=Buffer.from([137,80,78,71,13,10,26,10,0,0,0,0]);
function info(){const x={Krea2EditModelPatch:{},Krea2EditGroundedEncode:{}};for(const [n,k,v] of [['UNETLoader','unet_name',MODELS.unet],['CLIPLoader','clip_name',MODELS.clip],['VAELoader','vae_name',MODELS.vae],['LoraLoaderModelOnly','lora_name',MODELS.lora]])x[n]={input:{required:{[k]:[[v]]}}};return x;}
async function setup(t,options={}){const root=fs.mkdtempSync(path.join(os.tmpdir(),'ams-frame-test-'));if(options.before)options.before(root);let submitted=0;const fetchImpl=async(url,opts)=>{if(url.endsWith('/object_info'))return Response.json(info());if(url.endsWith('/prompt')){submitted++;return Response.json({prompt_id:'test'})}if(url.includes('/history/'))return Response.json({test:{outputs:{'15':{images:[{filename:'test.png',subfolder:'',type:'output'}]}}}});if(url.includes('/view?'))return new Response(png);throw Error('unexpected '+url)};
 const api=createFirstFrameApi({root,fetchImpl,pollMs:1}),server=http.createServer((q,s)=>api(q,s,new URL(q.url,'http://localhost').pathname));await new Promise(r=>server.listen(0,'127.0.0.1',r));t.after(async()=>{await new Promise(r=>server.close(r));fs.rmSync(root,{recursive:true,force:true})});return {root,submitted:()=>submitted,url:'http://127.0.0.1:'+server.address().port};}
test('real HTTP job writes candidate and snapshots without changing input assets',async t=>{const x=await setup(t),r=await fetch(x.url+'/api/first-frames',{method:'POST',body:JSON.stringify({projectId:'p',shotId:'s',prompt:'人坐在桌前',references:refs})});assert.equal(r.status,202);const job=await r.json();let result;for(let i=0;i<100;i++){result=await(await fetch(x.url+'/api/first-frames/'+job.id)).json();if(result.status==='completed')break;await new Promise(r=>setTimeout(r,5));}assert.equal(result.status,'completed');assert.equal(result.pass,1);assert.equal(result.completedPasses,1);assert.equal(x.submitted(),1);assert.equal(result.plan.references[0].file,refs[0].file);assert.ok(fs.existsSync(path.join(x.root,result.imageUrl)));});
test('restart polls saved prompt instead of submitting it again',async t=>{const x=await setup(t,{before(root){fs.mkdirSync(path.join(root,'frame-runs'));fs.writeFileSync(path.join(root,'frame-runs/frame_abc.json'),JSON.stringify({id:'frame_abc',plan:validatePlan({projectId:'p',shotId:'s',prompt:'测试',references:refs}),status:'running',pass:0,totalPasses:1,graphs:[],outputs:[],promptId:'test'}))}});let j;for(let i=0;i<100;i++){j=await(await fetch(x.url+'/api/first-frames/frame_abc')).json();if(j.status==='completed')break;await new Promise(r=>setTimeout(r,5));}assert.equal(j.status,'completed');assert.equal(x.submitted(),0);});
test('uncertain submission is not blindly resubmitted on restart',async t=>{const x=await setup(t,{before(root){fs.mkdirSync(path.join(root,'frame-runs'));fs.writeFileSync(path.join(root,'frame-runs/frame_abc.json'),JSON.stringify({id:'frame_abc',plan:validatePlan({projectId:'p',shotId:'s',prompt:'测试',references:refs}),status:'running',pass:0,totalPasses:1,graphs:[],outputs:[],submissionPending:true}))}});const j=await(await fetch(x.url+'/api/first-frames/frame_abc')).json();assert.equal(j.status,'failed');assert.match(j.error,/未知/);assert.equal(x.submitted(),0);});
