const {test}=require('node:test'),assert=require('node:assert/strict'),path=require('node:path');
const F=require('./film-framing'),E=require('./timeline-export-api'),S=require('./timeline-subtitles'),P=require('./film-preview-results'),Film=require('./film-api');
const id='film_'+'a'.repeat(16),url=kind=>'/film-runs/'+id+'/'+kind+'-0.mp4';
test('default crop remains padded, while explicit fill produces a full 16:9 composition',()=>{assert.match(F.cropFilter(17),/pad=1280:720/);assert.match(F.cropFilter(17,'fill'),/\(iw-ow\)\/2:0,scale=1280:720/);assert.doesNotMatch(F.cropFilter(17,'fill'),/pad=/);assert.throws(()=>F.cropFilter(17,'stretch'),/适配/);assert.throws(()=>F.cropFilter(21,'fill'),/0–20/)});
test('processed native clip paths keep the correct on-disk file and source caption identity',()=>{const run={shots:[{shotId:'s',dialogueEvents:[{type:'speech',text:'谢谢。'}]}]};for(const kind of ['clip','sound','framed']){assert.equal(E.sourceLocation(url(kind)).file,path.join(__dirname,'film-runs',id,kind+'-0.mp4'));assert.deepEqual(S.filmReference(url(kind)),{runId:id,index:0});assert.equal(S.sourceShot({url:url(kind),shotId:'s'},readId=>(assert.equal(readId,id),run)),run.shots[0])}});
test('processed path support rejects arbitrary files, external URLs, queries and traversal',()=>{for(const bad of ['/film-runs/'+id+'/run.json',url('framed')+'?other=1','https://external.test'+url('framed'),'/film-runs/'+id+'/../framed-0.mp4','/film-runs/'+id+'/framed-../../private.mp4'])assert.throws(()=>E.sourceLocation(bad));assert.throws(()=>S.sourceShot({url:url('framed'),shotId:'other'},()=>({shots:[{shotId:'s'}]})),/不匹配/)});
test('composition-only crop child preserves source media, voice binding and prior version',()=>{const parent={id,projectId:'p',title:'scene',status:'complete',shots:[{shotId:'s',ready:true,dialogueEvents:[],performanceAudio:{reference:'preserved'},cropBottomPercent:0}],qualityGate:true};const before=JSON.stringify(parent),child=Film.recomposePlan(parent,[{shotId:'s',cropBottomPercent:17,cropAspectMode:'fill'}]);assert.equal(child.shots[0].cropAspectMode,'fill');assert.equal(child.compositionOnly,true);assert.equal(child.shots[0].performanceAudio.reference,'preserved');assert.equal(child.parentRunId,id);assert.equal(JSON.stringify(parent),before);assert.throws(()=>Film.recomposePlan(parent,[{shotId:'s',cropAspectMode:'fill'}]),/同时明确/)});
test('only finished processed versions expose the cleaned clip; unfinished QA keeps raw video',()=>{const shot={shotId:'s',ready:true,jobId:'j',videoUrl:'raw.mp4',cropBottomPercent:17},data={shots:[{id:'s',projectId:'p'}]},run={id,projectId:'p',status:'complete',shots:[shot]};let out=P.merge(data,[run]);assert.equal(out.generations[0].videoUrl,url('framed'));assert.equal(out.generations[0].originalVideoUrl,'raw.mp4');assert.equal(out.generations[0].status,'待审核');assert.equal(P.merge(data,[{...run,status:'rendering'}]).generations[0].videoUrl,'raw.mp4');assert.equal(P.merge({...data,generations:out.generations},[run]).added,0)});
test('explicit deletion of either raw or derived result is respected',()=>{const run={id,projectId:'p',status:'complete',shots:[{shotId:'s',ready:true,jobId:'j',videoUrl:'raw.mp4',audioMode:'replacement'}]};for(const videoUrl of ['raw.mp4',url('sound')])assert.equal(P.merge({shots:[{id:'s',projectId:'p'}],deletedGenerationResults:[{projectId:'p',jobId:'j',videoUrl}]},[run]).added,0)});
