(function(root){
 const visualNotes=typeof module!=='undefined'&&module.exports?require('./reference-visual-notes'):root.ReferenceVisualNotes;
 function isStructured(value){const s=String(value||'').trim();return /^integrated_multimodal_description:/i.test(s)&&/overall_soundscape:[\s\S]*non_diegetic_music:/i.test(s)&&s.indexOf('overall_soundscape:')>s.indexOf('integrated_multimodal_description:');}
 function compile(shot,project,refs){
  const duration=Number(shot.dur);if(!Number.isFinite(duration)||duration<4||duration>15)throw Error('请设置 4–15 秒的镜头时长');
  const assets=refs.map(r=>`${r.name} (${r.kind}): ${visualNotes(r)}`).join('\n');
  const existingSound=/overall_soundscape:\s*([\s\S]*?)(?=non_diegetic_music:|$)/i.exec(shot.prompt||'')?.[1]?.trim();
  const sound=shot.soundscape?.trim()||existingSound||'Audible location ambience appropriate to the visible setting, plus distinct synchronized footsteps, clothing, object contact or vehicle sounds only when those actions occur. Keep effects below verified dialogue. No invented speech.';
  const layout=refs.filter(r=>r.kind==='characters').map(r=>r.name+': '+(shot.characterPositions?.[r.assetId||r.id]||'as composed in this shot')+'; match only this character’s own reference face and clothes. Wardrobe continuity: match the visible garment color, fabric, pattern, collar, sleeve length, fasteners and layers in this character’s reference image. Do not redesign clothing when the camera angle or setting changes. Change clothing only when this shot explicitly requires a costume change.').join('\n');
  const story=shot.storyBinding;
  // Planning facts are translated into the H3 prompt upstream. Repeating raw
  // story JSON inside a finished renderer prompt can become unwanted captions.
  const storyRules=story&&!isStructured(shot.prompt)?JSON.stringify({beats:story.beats.map(({action,before,after,place,time})=>({action,before,after,place,time})),facts:story.facts.map(({statement,delivery})=>({statement,delivery}))}):'';
  const constraints=`\n\n${storyRules?'Source-grounded action contract for this shot: '+storyRules+'\nShow the stated action and result in order; preserve counts, negations and object states. Context facts do not authorize additional speech. Exact visible text is supplied by post-production cards, never floating generated UI.':''}\nCharacter blocking (never swap identities):\n${layout}\nSelected visual assets for this shot only:\n${assets||'No visual asset specified.'}\nPreserve each selected identity and current wardrobe; do not import biographical clothing, other project assets or past actions. Silent screen content stays on the screen and is never spoken.\n${shot.continueFromShotId?'Continue from the supplied final frame of the preceding shot, preserving the camera, positions, wardrobe and objects. Perform only this shot’s new action. Speak only the verified dialogue for this shot; never repeat dialogue from the preceding shot.':''}\n`;
  if(/^integrated_multimodal_description:/i.test((shot.prompt||'').trim())){const prompt=shot.prompt.trim().replace(/overall_soundscape:[\s\S]*?(?=non_diegetic_music:|$)/i,'overall_soundscape: '+sound+'\n\n'),boundary=prompt.indexOf('overall_soundscape:');return boundary<0?prompt+constraints:prompt.slice(0,boundary)+constraints+prompt.slice(boundary);}
  return `integrated_multimodal_description: [Shot 1] Live-action, ${project?.bible?.style||'cinematic realism'}. One continuous ${duration}-second shot.\nAction: ${shot.script||''}\nComposition: ${shot.visual||shot.desc||''}\nCamera: ${shot.camera||''}\n${shot.prompt||''}\nDo not invent additional actions or dialogue.${constraints}\noverall_soundscape: ${sound} Spoken words and speakers are bound separately from the verified dialogue field.\n\nnon_diegetic_music: N/A`;
 }
 const api={compile,visualNotes,isStructured};if(typeof module!=='undefined'&&module.exports)module.exports=api;else root.ShotPrompt=api;
})(typeof globalThis!=='undefined'?globalThis:this);
