'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),cp=require('node:child_process'),crypto=require('node:crypto'),M=require('./sound-design'),R=require('./sound-design-render'),A=require('./audio-assets');
const F=process.env.FFMPEG_PATH||'C:\\AI\\Comfy UI\\ComfyUI\\.venv\\Lib\\site-packages\\imageio_ffmpeg\\binaries\\ffmpeg-win-x86_64-v7.1.exe';
function wav(seconds=2){const rate=48000,n=Math.round(seconds*rate),b=Buffer.alloc(44+n*4);b.write('RIFF');b.writeUInt32LE(b.length-8,4);b.write('WAVEfmt ',8);b.writeUInt32LE(16,16);b.writeUInt16LE(1,20);b.writeUInt16LE(2,22);b.writeUInt32LE(rate,24);b.writeUInt32LE(rate*4,28);b.writeUInt16LE(4,32);b.writeUInt16LE(16,34);b.write('data',36);b.writeUInt32LE(n*4,40);for(let i=0;i<n;i++){const v=Math.round(Math.sin(i*2*Math.PI*440/rate)*6000);b.writeInt16LE(v,44+i*4);b.writeInt16LE(v,46+i*4);}return b;}
function pcm(file){return cp.execFileSync(F,['-v','error','-i',file,'-f','s16le','-acodec','pcm_s16le','-ac','2','-ar','48000','pipe:1'],{windowsHide:true,maxBuffer:8*1024*1024});}
function rms(b,start,end,channel=0){let sum=0,n=0;for(let i=Math.floor(start*48000);i<Math.floor(end*48000);i++){sum+=(b.readInt16LE(i*4+channel*2)/32768)**2;n++;}return Math.sqrt(sum/n);}
test('real installed FFmpeg renders five exact stems, preserves source and ducks only music',{skip:!fs.existsSync(F)},async()=>{
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'ams-sound-test-'));try{const source=path.join(dir,'input.wav');fs.writeFileSync(source,wav());const before=fs.readFileSync(source),file='ams-audio-'+'a'.repeat(64)+'.wav',p=M.empty('encoding verification',4);p.masterDb=0;p.cues=[{id:'d',name:'test speech stand-in tone',trackId:'dialogue',file,sourceDuration:2,start:1,trimIn:0,trimOut:1,duration:1,loop:false,gainDb:0,pan:0,fadeIn:0,fadeOut:0},{id:'m',name:'test music tone',trackId:'music',file,sourceDuration:2,start:0,trimIn:0,trimOut:2,duration:4,loop:true,gainDb:-12,pan:0,fadeIn:0,fadeOut:0},{id:'s',name:'short effect',trackId:'effects',file,sourceDuration:2,start:3,trimIn:0,trimOut:.2,duration:.2,loop:false,gainDb:-6,pan:-1,fadeIn:.01,fadeOut:.03}];const r=await R.renderStems(p,path.join(dir,'out'),{resolve:()=>source});assert.equal(r.stems.length,5);assert.ok(Math.abs(r.seconds-4)<.001);assert.equal(r.bits,24);assert.ok(r.stems.every(s=>Math.abs(s.seconds-4)<.001));assert.deepEqual(fs.readFileSync(source),before);
 const music=pcm(r.stems.find(s=>s.trackId==='music').path);assert.ok(rms(music,1.3,1.7)<rms(music,.3,.7)*.4);assert.ok(rms(music,2.7,2.9)>rms(music,1.3,1.7)*2);
 const dialogue=pcm(r.stems[0].path);assert.equal(rms(dialogue,.1,.8),0);assert.ok(rms(dialogue,1.2,1.8)>.1);assert.equal(rms(dialogue,2.3,2.8),0);const effects=pcm(r.stems[2].path);assert.ok(rms(effects,3.02,3.16,0)>.01);assert.equal(rms(effects,3.02,3.16,1),0);
 assert.ok(r.peakDb<=0);assert.equal(r.userApproved,false);
 }finally{fs.rmSync(dir,{recursive:true,force:true});}
});
