let sourceSyncSession=null;
function sourceSyncOpen(id,proposal){
 if(typeof editingShotId!=='undefined'&&editingShotId){alert('请先保存分镜，或点击“保存分镜并同步原文”，以保留正在编辑的内容。');return}
 if(typeof TL!=='undefined'&&TL.dirty){alert('请先保存时间线面板中的修改，再编辑对应原文。');return}
 try{const {shot,project,script}=SourceSync.context(D,id);document.getElementById('sourceSyncDialog')?.remove();const dialog=document.createElement('dialog');dialog.id='sourceSyncDialog';dialog.className='source-sync-dialog';
 const excerpt=shot.sourceExcerpt||'',story=project.storyText??project.bible?.synopsis??'',match=excerpt&&story.includes(excerpt)&&story.indexOf(excerpt)===story.lastIndexOf(excerpt);
 sourceSyncSession={id,signature:SourceSync.signature(D,id),preview:null};
 dialog.innerHTML=`<header><div><small>${esc(project.name)} / ${esc(shot.scene||'场景')} / 镜头 ${shot.sequence||''}</small><h2>对应原文与同步</h2></div><button class="btn" onclick="sourceSyncClose()" aria-label="关闭原文编辑">关闭</button></header><p class="muted">来源：${esc(script?.title||'未关联剧本')}。本镜引用、来源剧本和最初故事分别保存。</p><div class="source-sync-columns"><section><h3>当前引用</h3><pre>${esc(excerpt||'暂无引用')}</pre><button class="btn" onclick="sourceSyncUseShot()">用已保存分镜的行动和对白起草</button><p class="muted">摄影、运镜与画面提示词不写入文学原文。</p></section><section><label for="sourceSyncExcerpt">修改后的对应原文</label><textarea id="sourceSyncExcerpt">${esc(proposal??excerpt)}</textarea></section></div><fieldset><legend>同步范围</legend><p>本镜对应原文始终保存。</p><label><input id="sourceSyncScript" type="checkbox" ${script?'checked':'disabled'}> 同时替换来源剧本中的这一段</label><label><input id="sourceSyncStory" type="checkbox" onchange="document.getElementById('sourceSyncStoryFields').hidden=!this.checked"> 同时修改最初的故事原文</label></fieldset><div id="sourceSyncStoryFields" hidden><p class="muted">故事与剧本可能措辞不同，请填写故事中要替换的完整原句及新文字。只替换唯一匹配位置。</p><div class="source-sync-columns"><label>故事中待替换原句<textarea id="sourceSyncStoryBefore">${esc(match?excerpt:'')}</textarea></label><label>替换后的故事文字<textarea id="sourceSyncStoryAfter">${esc(proposal??excerpt)}</textarea></label></div><details><summary>查看当前完整故事（用于核对原句）</summary><pre>${esc(story)}</pre></details></div><p id="sourceSyncStatus" role="status">${shot.sourceReviewRequired?'这段引用已与来源剧本不同，请核对并更新。':'修改后先预览同步范围，再保存。'}</p><div id="sourceSyncPreview"></div><footer><button class="btn" onclick="sourceSyncPreview()">预览同步修改</button><button id="sourceSyncApply" class="btn gold" disabled onclick="sourceSyncApply()">确认保存与同步</button></footer>`;
 dialog.addEventListener('input',()=>{if(sourceSyncSession)sourceSyncSession.preview=null;document.getElementById('sourceSyncApply').disabled=true;document.getElementById('sourceSyncPreview').innerHTML=''});
 dialog.addEventListener('cancel',event=>{event.preventDefault();sourceSyncClose()});document.body.append(dialog);dialog.showModal();document.getElementById('sourceSyncExcerpt').focus();
 }catch(e){alert(e.message)}
}
function sourceSyncClose(){const dialog=document.getElementById('sourceSyncDialog');if(dialog){dialog.close();dialog.remove()}sourceSyncSession=null}
function sourceSyncUseShot(){if(!sourceSyncSession)return;const {shot}=SourceSync.context(D,sourceSyncSession.id);document.getElementById('sourceSyncExcerpt').value=[shot.script||shot.desc,shot.dialogue].filter(Boolean).join('\n');sourceSyncSession.preview=null;document.getElementById('sourceSyncApply').disabled=true;document.getElementById('sourceSyncPreview').innerHTML='';document.getElementById('sourceSyncStatus').textContent='已起草，请核对动作和对白，再预览同步。'}
function sourceSyncValues(){return {excerpt:document.getElementById('sourceSyncExcerpt').value,script:document.getElementById('sourceSyncScript').checked,story:document.getElementById('sourceSyncStory').checked,storyBefore:document.getElementById('sourceSyncStoryBefore').value,storyAfter:document.getElementById('sourceSyncStoryAfter').value}}
function sourceSyncPreview(){try{const session=sourceSyncSession;if(SourceSync.signature(D,session.id)!==session.signature)throw Error('分镜或原文已经改变，请关闭后重新打开。');const values=sourceSyncValues(),plan=SourceSync.plan(D,session.id,values);session.preview=values;document.getElementById('sourceSyncPreview').innerHTML=`<h3>即将保存</h3><p>本镜引用${values.script?' + 来源剧本':''}${values.story?' + 故事原文':''}。${plan.affected.length?`另有 ${plan.affected.length} 个镜头引用受影响，将标记为需核对。`:''} 本镜及相连的承接镜头标记需重做，旧视频保留。</p><div class="source-sync-columns"><pre>${esc(plan.before.excerpt)}</pre><pre class="source-new">${esc(plan.after.excerpt)}</pre></div>${values.story?`<h4>故事原文替换</h4><div class="source-sync-columns"><pre>${esc(plan.before.story)}</pre><pre class="source-new">${esc(plan.after.story)}</pre></div>`:''}`;document.getElementById('sourceSyncApply').disabled=false;document.getElementById('sourceSyncStatus').textContent='预览已准备好。确认后一次保存，不调用 AI。'}catch(e){document.getElementById('sourceSyncStatus').textContent=e.message;document.getElementById('sourceSyncApply').disabled=true}}
function sourceSyncApply(){try{const session=sourceSyncSession;if(!session?.preview)return;let stored;try{stored=JSON.parse(localStorage.getItem('aimovie_data')||'null')}catch{throw Error('本地数据无法读取，请先备份后重试。')};stored=stored||D;stored={...stored,activeProjectId:D.activeProjectId};if(SourceSync.signature(D,session.id)!==session.signature||SourceSync.signature(stored,session.id)!==session.signature)throw Error('另一处已修改此分镜或原文，未覆盖。请关闭后重新核对。');const plan=SourceSync.plan(stored,session.id,session.preview);localStorage.setItem('aimovie_data',JSON.stringify(plan.next));Object.assign(D,plan.next);sourceSyncClose();renderAll();if(typeof tlMessage==='function')tlMessage('原文已保存并同步；受影响镜头已标记，旧视频保留。')}catch(e){document.getElementById('sourceSyncStatus').textContent=e.message}}
function saveStoryboardAndOpenSource(id){const proposal=[document.getElementById('board_script')?.value,document.getElementById('board_dialogue')?.value].filter(Boolean).join('\n');if(saveStoryboardShot(id))sourceSyncOpen(id,proposal)}
const sourceSyncEditor=storyboardShotEditor;
storyboardShotEditor=function(shot){return sourceSyncEditor(shot)+`<div class="source-edit-actions"><button class="btn gold" data-id="${esc(shot.id)}" onclick="saveStoryboardAndOpenSource(this.dataset.id)">保存分镜并同步原文…</button><span class="muted">先保存分镜，再预览原文修改范围。</span></div>`};
const sourceSyncInspector=tlInspector;
tlInspector=function(){sourceSyncInspector();const shot=tlCurrent()?.shot,host=document.getElementById('tl-inspector');if(!shot||!host||TL.mode!=='shots')return;const section=document.createElement('section');section.className='source-inspector';section.innerHTML=`<h3>对应剧本原文 ${shot.sourceReviewRequired?'<span class="source-warning">需核对</span>':''}</h3><p>${esc(shot.sourceExcerpt||'尚未填写对应原文')}</p><button class="btn" data-id="${esc(shot.id)}" onclick="sourceSyncOpen(this.dataset.id)">编辑原文 / 同步</button>`;host.prepend(section)};
const sourceSyncRenderShots=renderShots2;
renderShots2=function(){sourceSyncRenderShots();for(const button of document.querySelectorAll('#shots button[onclick*="editingShotId=this.dataset.id"]')){const id=button.dataset.id;if(!id)continue;const edit=document.createElement('button');edit.className='btn';edit.textContent='编辑对应原文';edit.onclick=()=>sourceSyncOpen(id);button.after(edit)}};
const sourceSyncDialogue=shotDialogueEvents;
shotDialogueEvents=function(shot){if(shot.sourceReviewRequired)throw Error('此镜引用的原文已被其他镜头修改，请先编辑并核对对应原文。');return sourceSyncDialogue(shot)};
const sourceSyncScripts=renderScripts;
renderScripts=function(){sourceSyncScripts();for(const block of document.querySelectorAll('.story-shot')){const id=block.querySelector('textarea[data-id]')?.dataset.id;if(!id)continue;const button=document.createElement('button');button.className='btn';button.textContent='编辑引用 / 同步原文';button.onclick=()=>sourceSyncOpen(id);block.append(button)}};
const sourceHierarchyRender=renderAll;
renderAll=function(){sourceHierarchyRender();for(const id of ['scripts','assets','timeline']){const page=document.getElementById(id);if(!page)continue;page.querySelector('.workspace-path')?.remove();const path=document.createElement('nav');path.className='workspace-path';path.setAttribute('aria-label','创作流程导航');path.innerHTML=`<span>${esc(activeProject().name)}</span>${[['scripts','1 故事与剧本'],['assets','2 资产库'],['timeline','3 时间线制作']].map(([target,label])=>`<button class="btn ${id===target?'gold':''}" onclick="go('${target}')" ${id===target?'aria-current="page"':''}>${label}</button>`).join('')}`;page.prepend(path)}};
