let openaiSessionKey='',openaiServerConfigured=false;
const textAIModels=['deepseek-flash','deepseek-v4-pro','gpt-5.4','gpt-5.4-mini','gpt-5.4-nano','gpt-5-mini'];
function textAIHeaders(model){const key=String(model||'').startsWith('gpt-')?openaiSessionKey:screenplayApiKey;return key?{Authorization:'Bearer '+key}:{}}
function textAISelect(value){if(!value)return;saveScreenplayField('screenplayModel',value);renderScripts()}
function textAISettings(){const p=activeProject(),model=p.screenplayModel||'deepseek-flash';return `<div class="card"><h2>AI 模型 · 剧本 / 分镜 / H3 提示词</h2><label>选择模型<select aria-label="AI 文本模型" onchange="textAISelect(this.value)">${[...new Set([...textAIModels,model])].map(m=>`<option value="${esc(m)}" ${m===model?'selected':''}>${m.startsWith('gpt-')?'OpenAI · ':'DeepSeek · '}${esc(m)}</option>`).join('')}</select></label><p class="muted">当前使用 ${model.startsWith('gpt-')?'OpenAI 官方接口':'DeepSeek 接口'}。模型可用性以对应 API 账户权限为准。</p><details><summary>连接与密钥</summary><div class="formgrid"><label>OpenAI API Key<input type="password" autocomplete="off" aria-label="OpenAI API Key" placeholder="${openaiSessionKey?'本次会话已填写':openaiServerConfigured?'服务器已配置':'填写 OpenAI API Key'}" oninput="openaiSessionKey=this.value.trim()"></label><label>DeepSeek API Key<input type="password" autocomplete="off" aria-label="DeepSeek 独立密钥" placeholder="${screenplayApiKey?'本次会话已填写':screenplayServerConfigured?'服务器已配置':'填写 DeepSeek API Key'}" oninput="screenplayApiKey=this.value.trim()"></label></div><p class="muted">两个服务分别使用各自的密钥。页面输入仅保留在当前会话，刷新后清除；服务器可配置 OPENAI_API_KEY 和 DEEPSEEK_API_KEY。</p><label>自定义模型名称<input aria-label="自定义文字模型" value="${esc(model)}" onchange="textAISelect(this.value.trim())"></label></details></div>`}
const textAIRender=renderScripts;
renderScripts=function(){textAIRender();const root=document.getElementById('scripts');root.querySelector('h1 + p').insertAdjacentHTML('afterend',textAISettings());document.getElementById('screenplayApiKey')?.closest('details')?.setAttribute('hidden','');
 for(const el of root.querySelectorAll('.story-flow p'))if(!el.id)el.textContent=el.textContent.replaceAll('DeepSeek','所选 AI 模型');
};
if(location.protocol!=='file:')fetch('/api/screenplay/config').then(r=>r.json()).then(c=>{openaiServerConfigured=!!c.openaiConfigured}).catch(()=>{});
const textAIShots=renderShots2;
renderShots2=function(){textAIShots();const details=document.getElementById('boardApiKey')?.closest('details');if(details)details.innerHTML='<summary>AI 模型连接</summary><p>剧本、分镜和提示词共用“故事与剧本”里的模型与独立密钥设置。</p><button class="btn" onclick="go(\'scripts\')">设置 AI 模型</button>'};
