let openaiSessionKey='',openaiServerConfigured=false;
let textAIStatus={local:{},configured:{}},textAIMessage='',textAIBusy=false,textAIEditing=false;
const textAIModels=['deepseek-flash','deepseek-v4-pro','gpt-5.4','gpt-5.4-mini','gpt-5.4-nano','gpt-5-mini'];
const textAIProvider=model=>String(model||'').startsWith('gpt-')?'openai':'deepseek';
function textAIHeaders(){return {}}
function textAISelect(value){if(!value||textAIBusy)return;openaiSessionKey='';screenplayApiKey='';textAIEditing=false;textAIMessage='';saveScreenplayField('screenplayModel',value);renderScripts()}
function textAIInput(provider,value){if(provider==='openai')openaiSessionKey=value.trim();else screenplayApiKey=value.trim();}
function textAIRefresh(){const card=document.getElementById('textAISettings');if(card)card.outerHTML=textAISettings();}
function textAISettings(){
 const model=activeProject().screenplayModel||'deepseek-flash',provider=textAIProvider(model),label=provider==='openai'?'OpenAI':'DeepSeek',local=textAIStatus.local[provider],configured=textAIStatus.configured[provider];
 return `<div class="card" id="textAISettings"><h2>AI 模型 · 剧本 / 分镜 / H3 提示词</h2><label>选择模型<select aria-label="AI 文本模型" ${textAIBusy?'disabled':''} onchange="textAISelect(this.value)">${[...new Set([...textAIModels,model])].map(m=>`<option value="${esc(m)}" ${m===model?'selected':''}>${m.startsWith('gpt-')?'OpenAI · ':'DeepSeek · '}${esc(m)}</option>`).join('')}</select></label><p>${label} Key：${local?'已加密保存在本机':configured?'已通过服务器配置':'尚未保存'}</p>${!configured||textAIEditing?`<form autocomplete="off" onsubmit="event.preventDefault();textAISave()"><label>${label} API Key<input type="password" id="ams-${provider}-credential" name="ams-${provider}-api-token" aria-label="${label} API Key" autocomplete="new-password" spellcheck="false" autocapitalize="off" ${textAIBusy?'disabled':''} placeholder="粘贴 ${label} 的 API Key" oninput="textAIInput('${provider}',this.value)"></label><button class="btn gold" type="submit" ${textAIBusy?'disabled':''}>保存到本机</button></form>`:`<button class="btn" ${textAIBusy?'disabled':''} onclick="textAIEditing=true;textAIRefresh()">更换 ${label} Key</button>`}<button class="btn" ${textAIBusy?'disabled':''} onclick="textAITest()">测试当前模型</button>${local?`<button class="btn" ${textAIBusy?'disabled':''} onclick="textAISave(true)">删除本机 ${label} Key</button>`:''}<p class="muted">DeepSeek 与 OpenAI 分别保存；刷新、重启或换浏览器无需重填。密钥由当前 Windows 用户加密保护，不写入项目导出或 GitHub。连接测试会发送一条简短请求，可能产生少量 API 费用。</p><p id="textAIStatus" role="status">${esc(textAIMessage)}</p><details><summary>自定义模型</summary><label>模型名称<input aria-label="自定义文字模型" value="${esc(model)}" ${textAIBusy?'disabled':''} onchange="textAISelect(this.value.trim())"></label></details></div>`;
}
async function textAILoadStatus(){const r=await fetch('/api/ai/settings',{cache:'no-store'}),out=await r.json();if(!r.ok)throw Error(out.error||'无法读取本地设置');textAIStatus=out;openaiServerConfigured=!!out.configured.openai;screenplayServerConfigured=!!out.configured.deepseek;}
async function textAISave(remove=false){
 if(textAIBusy)return false;const provider=textAIProvider(activeProject().screenplayModel),field=document.getElementById('ams-'+provider+'-credential'),key=remove?'':(field?.value||'').trim();
 if(!remove&&!key){textAIMessage='请先输入当前服务的 API Key';document.getElementById('textAIStatus').textContent=textAIMessage;return false;}
 textAIBusy=true;
 try{const r=await fetch('/api/ai/settings',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({provider,key})}),out=await r.json();if(!r.ok)throw Error(out.error||'保存失败');textAIStatus=out;openaiServerConfigured=!!out.configured.openai;screenplayServerConfigured=!!out.configured.deepseek;openaiSessionKey='';screenplayApiKey='';textAIEditing=false;textAIMessage=remove?'本机保存的密钥已删除。':'已加密保存到本机，刷新后仍可使用。';textAIRefresh();return true;}
 catch(e){textAIMessage=e.message;document.getElementById('textAIStatus').textContent=textAIMessage;return false;}
 finally{textAIBusy=false;document.getElementById('textAISettings')?.querySelectorAll('button,input,select').forEach(el=>el.disabled=false);}
}
async function textAITest(){if(textAIBusy)return;const model=activeProject().screenplayModel||'deepseek-flash',provider=textAIProvider(model),input=document.getElementById('ams-'+provider+'-credential');if(input?.value.trim()&&!await textAISave())return;textAIBusy=true;textAIMessage='正在测试当前模型…';textAIRefresh();try{const r=await fetch('/api/ai/test',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({model}),signal:AbortSignal.timeout(65000)}),out=await r.json();if(!r.ok)throw Error(out.error||'测试失败');textAIMessage=out.message;}catch(e){textAIMessage=e.message}finally{textAIBusy=false;textAIRefresh()}}
const textAIRender=renderScripts;
renderScripts=function(){textAIRender();const root=document.getElementById('scripts');root.querySelector('h1 + p').insertAdjacentHTML('afterend',textAISettings());document.getElementById('screenplayApiKey')?.closest('details')?.setAttribute('hidden','');document.getElementById('screenplayApiKey')?.remove();for(const el of root.querySelectorAll('.story-flow p'))if(!el.id)el.textContent=el.textContent.replaceAll('DeepSeek','所选 AI 模型');};
if(location.protocol!=='file:')textAILoadStatus().then(()=>{if(document.getElementById('scripts')?.classList.contains('on')&&!document.querySelector('#textAISettings input:focus'))textAIRefresh()}).catch(()=>{textAIMessage='本地设置服务未连接，请确认工作室服务已启动。'});
const textAIShots=renderShots2;
renderShots2=function(){textAIShots();const details=document.getElementById('boardApiKey')?.closest('details');if(details)details.innerHTML='<summary>AI 模型连接</summary><p>剧本、分镜和提示词共用本机保存的模型密钥。</p><button class="btn" onclick="go(\'scripts\')">设置 AI 模型</button>'};
